# docker-compose for tokengenerator-alpine - due to technical reasons, only works with catspeed fork!
version: "3"
services:

  tokengenerator:
    build:
      context: .
      dockerfile: docker/Dockerfile
    # todo: upload initial image and update following line
    #image: "debian:latest"
    init: true
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    deploy:
      resources:
        limits:
          # modify CPU limit for token generator as you please
          cpus: '0.75'
          # modify MEMORY limit for token generator as you please
          memory: 100M
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      # to avoid conflicts, ssh is on port external 2222 internal 22.
      # change external to 22 if you have no SSH server on host machine.
      # command to connect is:
      # ssh -p 2222 root@172.91.0.5
      - 2222:22
      # changes inside conatiner will not be saved
      # mainly for watching 'htop', running redis-cli commands, etc.
    args:
        # set your root password (for ssh, etc)
        ROOTPASSWORD: "debianftw!"
    environment:
     # True: use only token server, False: use pre-generated tokens (one or the other, not both)
     - TOKEN_SERVER_ENABLED=false
     # redis host, should not need change unless you've changed it
     - REDIS_HOST=172.91.0.52
     # redis port, should not need change unless you've changed it
     - REDIS_PORT=6379
     # pgsql host, should not need change unless you've changed it
     - PGSQL_HOST=172.91.0.51
     # pgsql port, should not need change unless you've changed it
     - PGSQL_PORT=5432
     # pgsql user, should not need change unless you've changed it
     - PGSQL_USER=kemal
     # pgsql password, should not need change unless you've changed it
     - PGSQL_PASS=kemal
     # pgsql database, should not need change unless you've changed it
     - PGSQL_DB=invidious
     # IMPORTANT: list each instance id here separated by |
     # Ex. instance1|instance2|instance3
     - INSTANCES=instance1|instance2|instance3
     # IMPORTANT: enter the expiry time for USER tokens in seconds (set it same as invidious config)
     - USER_EXPIRY=900
     # IMPORTANT: enter the number of ANON tokens to generate 
     # minimum is what is set in invidious configuration, can generate more too ahead of time
     - NUM_TOKENS=2500
     # IMPORTANT: enter the expiry time for ANON tokens in seconds (set it same as invidious config)
     - ANON_EXPIRY=43200
    networks:
      # IMPORTANT: if you cloned the project with dir name as anything other than 'invidious' change this line
      tokengenerator-debian:
        # IMPORTANT: this is the IP that you will use to access this docker container
        ipv4_address: 172.95.0.5
      # IMPORTANT: if you cloned the project with dir name as anything other than 'invidious' change this line
      invidious-mooleshacat_services_network:
        # just a formality. I always set static IP on every machine I own
        # in the case of docker, it cuts out un-needed and un-reliable docker embedded DNS
        ipv4_address: 172.91.0.5

networks:
  # tokengenerator network for standalone usage
  tokengenerator-debian:
    ipam:
      driver: default
      config:
        - subnet: "172.95.0.0/24"
  # IMPORTANT: if you cloned the project with dir name as anything other than 'invidious' change this line
  # This is for INVIDIOUS catspeed fork integration.
  # Currently I've cloned catspeed fork to directory: invidious-mooleshacat/
  # services_network is the network / subnet for services (redis, pgsql, unbound, haproxy, etc.)
  invidious-mooleshacat_services_network:
    external: true

# todo: remove invidious integration network, catspeed-cc/invidious will have integration example
