# docker-compose for tokengenerator-alpine - due to technical reasons, only works with catspeed fork!
version: "3"
services:

  tokenserver-debian-1:
    build:
      context: .
      dockerfile: docker/Dockerfile
#    image: "catspeedcc/tokenserver-debian:latest"
    network_mode: "service:gluetun-1"
    init: true
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    deploy:
      resources:
        limits:
          # modify CPU limit for token generator as you please
          cpus: '0.75'
          # modify MEMORY limit for token generator as you please
          memory: 100M
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      # unique server identification
      - SERVER_ID=catspeed1
      # IMPORTANT: enter the number of ANON tokens to generate 
      - NUM_TOKENS=10000
    volumes:
      - ./tokenserver-data/redis-data/:/var/lib/redis/
    secrets:
     - tokenserver-root-password
    depends_on:
      - gluetun-1

  gluetun-1:
    image: ghcr.io/qdm12/gluetun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun
#    ports:
#      - 8888:8888/tcp # HTTP proxy (expose to host is optional)
#      - 8080:8080/tcp # Control port (expose to host is optional)
    volumes:
      - /docker/gluetun/data:/gluetun
    environment:
#      - LOG_LEVEL=debug
      - HTTPPROXY=on
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=YOUR_OPENVPN_USER
      - OPENVPN_PASSWORD=YOUR_OPENVPN_PASSWORD
      - OPENVPN_PROTOCOL=tcp
      - OPENVPN_MSSFIX=1400
      - SERVER_COUNTRIES=United States
      - UPDATER_PERIOD=24h
      - UPDATER_VPN_SERVICE_PROVIDERS=protonvpn
      - DNS_ADDRESS=1.1.1.1
      - TZ=America/Toronto
    networks:
      tokenserver-debian:
        ipv4_address: 172.54.0.5

secrets:
  tokenserver-root-password:
    file: ./tokenserver-data/secrets/tokenserver-root-password

networks:
  # tokengenerator network for standalone usage
  tokenserver-debian:
    ipam:
      driver: default
      config:
        - subnet: "172.54.0.0/24"
