# docker-compose for tokengenerator-alpine - due to technical reasons, only works with catspeed fork!
version: "3"
services:

  tokengenerator:
    build:
      context: .
      dockerfile: docker/Dockerfile
    #image: "alpine:latest"
    init: true
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    command: sleep inf
    #volumes:
     #- ./redis-data:/data
    environment:
     - REDIS_HOST=172.91.0.52
     - REDIS_PORT=6379
     - INSTANCES=instance1|instance2|instance3
    networks:
      invidious-mooleshacat_services_network:
        ipv4_address: 172.91.0.5

networks:
  invidious-mooleshacat_services_network:
    external: true
