iv-org/invidious
@unixfox

I don't appreciate how you treat me. I have been nothing but nice and respectful to everyone. I respect you, samantaz, syeopite and Fijxu especially. But lately I have been getting general snobbiness and disrespect from you and a few others.

I have come a very long way myself, and still am a noob. However to have my own fork and have made a token generator that works, which currently even iv-org does not yet have, I know I am succeeding and I don't need you to tell me I'm not. You may think the things I do are weird (whatever that means) but my fork is no different from Fijxu's fork. My fork only has a few simple template mods, and the token generator. Fijxu has the same and many more modifications.

If you want to build an open source program to install every single open source fork except for mine for retarded reasons, then I guess go for it. It's not really "open" to be discouraging people from making their own decisions and installing the forks they choose. If your tool was so great, it wouldn't matter blacklisting my fork, because according to you it sucks and no one would install it correct? And if they installed it and had problems they could just install a different fork using your tool if it was so easy... Blacklisting me only shows you hold some sort of grudge against me, and it looks bad on you and the project.


Anyways you have two options.

1) Keep your mouth shut unless you have something nice to say. Keep your preferences to yourself also. I have my own preferences.
2. Delist catspeed, and I will go unofficial, and remove the donation link for invidious, and cease my donations to invidious. I have a lot more than just $30 USD.

If you choose option 2, I will be staying in main and talking all I wish about po_tokens. After all, it was you , or samantaz, who was just talking about them in main. It's also on github and in the documentation. Not to mention the users that keep asking about them. And if I am delisted, I can do as I please. No one will complain at me again for this because everyone talks about it in main, including you.

I will of course when you admit you were wrong, give you another chance, and re-list catspeed. Because I am not that big of an asshat.


I thought this community would be nicer than this. I thought the invidious team would be more respectful, and encourage learning. Especially noobs to Crystal. I guess I was wrong.

If you can't respect the fact that I am learning, what's that say about you?

I will keep my mouth shut until you make a decision. If you don't make one in 72 hours from now, I will.

I'll see myself out of this channel, or you can kick me. Insult me all you wish, I will not be discouraged. That should be evident by now.

In the meantime, I'm going back to work. I have better things to do with my time than get shit on by you.

P.S. I've removed token generator, now my fork is only template mods. Token generator is in separate project now. If you still somehow think my fork is "weird" you are calling every public instance owners forks weird also. You can check my code while you cope & seethe https://gitea.catspeed.cc/catspeed-cc/tokengenerator-debian

EOF

